Add cloudbuild configuration.
PalmStoneGames/kube-cert-manager pull request #59
Opened 2017-04-20 18:47 UTC by nanliu

2017-04-20 18:48 UTC, nanliu commented
This provides a config for building and deploying this as a container into gcr.io.

2017-04-20 19:01 UTC, luna-duclos commented
Could you add some instructions on how to use this ?

2017-04-20 19:02 UTC, luna-duclos commented
See https://github.com/PalmStoneGames/kube-cert-manager/blob/master/codebuild/README.md for an example on how AWS cloudbuild is documented.
We also probably want to make the distinction clear between google and AWS cloudbuild somehow

2017-04-21 18:29 UTC, nanliu commented
I've included some documentation. Let me know if it's sufficient.

2017-04-21 19:58 UTC, luna-duclos commented
Will merge this soon, probably tomorrow.

2017-04-24 21:46 UTC, ahmetb requested changes

2017-04-24 21:46 UTC, ahmetb commented on CONTAINER_BUILDER.md
> +
Can you also add manual one-off build command please? This doesn't require forking the repo.

    gcloud container builds submit --config cloudbuild.yaml .

2017-04-26 20:50 UTC, nanliu commented on CONTAINER_BUILDER.md
> +
This has been added to the section below.

2017-04-26 20:53 UTC, ahmetb commented on CONTAINER_BUILDER.md
> +To review jobs created by container builder:
@nanliu you don't need this as `gcloud container builds submit ` streams the build log and the result.

2017-04-26 20:53 UTC, ahmetb commented on CONTAINER_BUILDER.md
> +
thanks

2017-04-27 17:56 UTC, nanliu commented on CONTAINER_BUILDER.md
> +To review jobs created by container builder:
This is for jobs triggered by github PR and not submitted manually.

2017-04-27 17:58 UTC, ahmetb commented on CONTAINER_BUILDER.md
> +To review jobs created by container builder:
You're listing it under the CLI build though. Which gives the impression that manual build submit and listing the build result are related somewhat :)

2017-05-24 16:51 UTC, merged